### ISSUE TITLE
RESEARCH: Phase out FPL

### ISSUE THREAD

**Issue by rhlsthrm** [Midas-Protocol/monorepo#30]
## Background

We need to create a subgraph implementation to be consumed by our UI.

### Linked Issues & Documentation

Use `schema.graphql` from here: https://github.com/davekaj/lending-subgraph-standard

## Definition Of Done

MVP implementation should drive the UI and move away from some of the Fuse pool queries. Focus on implementing parts of the mapping that populate the schemas for the UI that we need.

## Tasks

- [ ] Create `subgraph` module in our new monorepo that can deploy subgraphs to any chain we are on. Use [Connext](https://github.com/connext/nxtp/tree/main/packages/subgraph) implementation as reference.
- [ ] Write queries in SDK (again see [Connext](https://github.com/connext/nxtp/blob/main/packages/sdk/src/subgraph/queries.ts) for examples).
- [ ] Generate code for subgraphs [example](https://github.com/connext/nxtp/blob/main/packages/sdk/package.json#L16).
- [ ] Pull generated code into SDK and replace some of the SDK functions (maybe have two sets of functions, one that queries subgraph directly and one that queries contracts?
