### ISSUE TITLE
Initial Chain Deployment: Polygon

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#354]
## Chain Information

https://polygon.technology/

Link to Chain Developer docs: (https://polygon.technology/developers)

Native Wallet: MM

**Mainnet**
Chain Name: Polygon 
Chain ID: 137
RPC URL:  *XXX*
ChainExplorer: https://polygonscan.com/
Wrapped Native Token: https://polygonscan.com/token/0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270

**Ecosystem**
Uniswap-clone project name: XXX <br>
Uniswap-clone docs: XXX <br>

## Tasks
*Please mark the tasks below, as appropriate.  Then link supporting Github items together using:* ![Screenshot of Github Link Button](https://user-images.githubusercontent.com/103433798/169572470-b7e31053-afab-4225-9816-6403193b86b3.png)

- [ ] Please use the link below to add initial set of assets <br>
   - [Link to Custom Asset Template](https://github.com/Midas-Protocol/monorepo/issues/new?assignees=&labels=Custom+Asset+Support&template=custom-asset-support.md&title=Support+Asset+%24XXX)
- [X] Create chain-specific deploy script inside `chainDeploy`
- [ ] Add the supported chain and its parameters to the [network configs](https://github.com/Midas-Protocol/contracts/blob/main/src/network.ts) of the SDK 
   - [ ] Blocks per year
   - [ ] Chain-specific addresses
   - [ ] Supported oracles
- [ ] Add network to hardhat config
- [ ] Run deploy script, export deployments and commit both `deployments.json` and deployments artifacts
- [ ] Redeploy SDK
- [ ] SDK
   - [ ] Add supported assets to `chainConfig/supportedAssets`
   - [ ] Add chain ids to `SupportedChains` enum
- [ ] UI
   - [ ] Add Polygon Mainnet to `<SwitchNetworkModal/>`
   - [ ] Add `ChainMetadata` for Mainnet
   - [ ] Make sure Mainnet is Listed in `SupportedChains`
   - [ ] Deactivate Mainnet via `netlify.toml` until specific release

**Comment by NikMidas** [comment]
This has been completed
