### ISSUE TITLE
Replace Native Asset with Wrapped Version for Pool Admins

### ISSUE THREAD

**Issue by Pczek** [Midas-Protocol/monorepo#88]
## Background

The Native Asset for each chain is not compatible with the ERC20 Standard and therefore needs special treatment. This is combersome and can lead to errors. We've decided to discontinue support for the native asset of each chain and replace it by the "Wrapped" version of it. This is just a ERC20 token representing the native asset. For ETH it would be WETH(Wrapped Ether) https://weth.io/ .

For the completion of this Ticket we want to prevent the Pool admin to add the native asset, so preventing adding an asset with the 0x000...000 address, which was used to add the native asset.

<img width="480" alt="Screenshot 2022-05-24 at 10 05 58" src="https://user-images.githubusercontent.com/839848/169981620-f4b4f54f-d128-4619-a604-bde3532ecfa8.png">

At best this button to "add ETH address" should be replaced to add the address of the wrapped version of the native asset. The address of the wrapped versions of the native token is different for each chain and need to be researched and could then be added to the frontend code directly. No need to add it to

### Linked Issues & Documentation

+ https://weth.io/

## Tasks

- [ ] Remove Button to add Native asset Address aka Zero Address
- [ ] Replace Button with adding the Native Asset Wrapped version for that Chain (WBNB on BSC)
- [ ] Make sure zero Address can't be added even if inputed manually
